clap_std: Remove unused import
error: unused import: `arg`
 --> framework_lib/src/commandline/clap_std.rs:6:12
  |
6 | use clap::{arg, command, Arg, Args, FromArgMatches};
  |            ^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unused_imports)]`

Signed-off-by: Daniel Schaefer <dhs@frame.work>