flake: cross-windows: Add mingw
> cargo build --target x86_64-pc-windows-gnu  -p framework_tool

error: failed to run custom build command for `framework_tool v0.6.1 (/home/zoid/clone/framework-system/framework_tool)`

Caused by:
  process didn't exit successfully: `/home/zoid/clone/framework-system/target/debug/build/framework_tool-c329672d9ff2ef23/build-script-build` (exit status: 101)
  --- stderr

  thread 'main' (120396) panicked at framework_tool/build.rs:7:14:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: error calling dlltool 'x86_64-w64-mingw32-dlltool': No such file or directory (os error 2)

Signed-off-by: Daniel Schaefer <dhs@frame.work>