rgbkbd: Name arguments
Now when running `framework_tool --rgbkbd` instead of

```
error: 2 values required by '--rgbkbd <RGBKBD> <RGBKBD>...'; only 1 was provided
```

it says:

```
error: 2 values required by '--rgbkbd <START> <HEXCOLOR>...'; only 1 was provided
```

Signed-off-by: Daniel Schaefer <dhs@frame.work>